// ignore: constant_identifier_names
const BASEURL = 'http://127.0.0.1:4000/apis';
// const BASEURL = 'https://ea7c-103-119-178-7.ngrok-free.app/apis';
const allCoursesApiEndpoint = 'product/get-products-all/';
const allPopularCoursesApiEndpoint = 'product/get-popular-products/';
const allCategoryApiEndpoint = 'category/get-category-list/';
const allBannersApiEndpoint = 'banner/get-banners/';
const getSessionApiEndpoint = 'session/get-session-details/';
const getProductReviewEndpoint = 'review/get-product-review/';
const getPurchaseDetailsEndpoint = 'product/get-purchase-details/';
const userSiginEndpoint = 'users/login/';
const userSignupEndpoint = 'users/register/';
const purchaseProductEndpoint = 'product/purchase-product/';
const markSessionCompletedEndpoint = 'session/mark-session-completed/';
const markLevelompletedEndpoint = 'session/mark-level-completed/';
const getLevelRecordEndpoint = 'session/get-level-record/';
const getSessionRecordEndpoint = 'session/get-session-record/';
const markCourseCompletedEndpoint = 'product/mark-completed/';
const getCompletedCourseEndpoint = 'product/get-completed-courses/';
